version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bigdata_snowflake_db
    environment:
      POSTGRES_DB: pet_store_analytics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./csvdata:/csvdata